quarkus.config.locations=configProcesador.yml
quarkus.native.additional-build-args=--report-unsupported-elements-at-runtime,-H:+ReportExceptionStackTraces,--initialize-at-run-time=net.sf.jasperreports.renderers,--initialize-at-run-time=org.apache.batik.bridge
