quarkus.config.locations=configProcesador.yml
quarkus.native.additional-build-args=--report-unsupported-elements-at-runtime,\
  -H:+ReportExceptionStackTraces,\
  --initialize-at-run-time=net.sf.jasperreports,\
  --initialize-at-run-time=org.apache.batik,\
  --initialize-at-run-time=org.apache.xmlgraphics,\
  --initialize-at-run-time=org.mozilla.javascript,\
  --initialize-at-run-time=org.mozilla.classfile,\
  --initialize-at-run-time=org.w3c.dom.svg,\
  --initialize-at-run-time=org.w3c.css.sac,\
  --initialize-at-run-time=sun.java2d,\
  --initialize-at-run-time=sun.font,\
  --initialize-at-run-time=sun.awt,\
  --initialize-at-run-time=java.awt,\
  --initialize-at-run-time=javax.imageio,\
  --initialize-at-run-time=com.sun.imageio,\
  --initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl,\
  --initialize-at-run-time=org.apache.http.impl.auth,\
  --initialize-at-run-time=com.ibm.icu
